# Generated by Django 5.2.7 on 2025-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('CNIB', models.CharField(max_length=100)),
                ('Transaction', models.CharField(max_length=100)),
                ('Operateur', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('Montant', models.CharField(max_length=100)),
            ],
        ),
    ]
