# Generated by Django 5.2.7 on 2025-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('CNIB', models.CharField(max_length=50)),
                ('type_transaction', models.CharField(choices=[('Dépôt', 'Dépôt'), ('Retrait', 'Retrait')], max_length=10)),
                ('operateur', models.CharField(choices=[('Wave', 'Wave'), ('Orange Money', 'Orange Money'), ('Moov', 'Moov'), ('Telecel', 'Telecel'), ('Sank', 'Sank')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
