# Generated by Django 5.2.7 on 2025-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_transaction_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
